# Generated by Django 5.1.4 on 2024-12-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'article.", max_length=255)),
                ('link', models.URLField(help_text="Lien vers l'article original.", unique=True)),
                ('content', models.TextField(blank=True, help_text="Résumé ou contenu de l'article.", null=True)),
                ('published_at', models.DateTimeField(help_text="Date de publication de l'article.")),
                ('feed', models.ForeignKey(help_text='Flux RSS associé à cet article.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='feeds.rssfeed')),
            ],
        ),
    ]
