# Generated by Django 5.1.6 on 2025-05-15 08:37

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '__first__'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'article.", max_length=255)),
                ('link', models.URLField(help_text="Lien vers l'article.")),
                ('content', models.TextField(blank=True, help_text="Contenu de l'article.", null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text="Date de publication de l'article.", null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, help_text="Dernière consultation de l'article.", null=True)),
                ('feed', models.ForeignKey(help_text='Flux RSS associé à cet article.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='feeds.rssfeed')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date à laquelle l'article a été ajouté aux favoris.")),
                ('user', models.ForeignKey(help_text="Utilisateur qui a ajouté l'article aux favoris.", on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(help_text='Article marqué comme favori.', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='articles.rssfeedentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
