# Generated by Django 5.1.4 on 2024-12-16 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeedentry',
            name='content',
            field=models.TextField(blank=True, help_text="Contenu de l'article.", null=True),
        ),
        migrations.AlterField(
            model_name='rssfeedentry',
            name='link',
            field=models.URLField(help_text="Lien vers l'article."),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date à laquelle l'article a été ajouté aux favoris.")),
                ('article', models.ForeignKey(help_text='Article marqué comme favori.', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='articles.rssfeedentry')),
                ('user', models.ForeignKey(help_text="Utilisateur ayant marqué l'article comme favori.", on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
