# Generated by Django 5.1.4 on 2024-12-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_rssfeedentry_content_alter_rssfeedentry_link_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
