# Generated by Django 5.1.6 on 2025-02-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_favorite_unique_together_remove_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeedentry',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, help_text="Dernière consultation de l'article.", null=True),
        ),
    ]
