# Generated by Django 5.1.4 on 2025-01-29 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_favorite_unique_together_remove_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeedentry',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date de publication de l'article."),
        ),
    ]
