# Generated by Django 5.1.6 on 2025-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rssfeedentry_last_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeedentry',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text="Date de publication de l'article.", null=True),
        ),
    ]
