# Generated by Django 5.1.6 on 2025-05-15 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la catégorie.')),
                ('image', models.ImageField(blank=True, help_text='Image associée à la catégorie.', null=True, upload_to='categories/')),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur propriétaire de la catégorie (null = catégorie globale).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du flux RSS.', max_length=255)),
                ('url', models.URLField(help_text='URL du flux RSS.', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description du flux RSS.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout du flux RSS.")),
                ('is_public', models.BooleanField(default=False, help_text='Indique si le flux RSS est public ou privé.')),
                ('category', models.ForeignKey(blank=True, help_text='Catégorie associée au flux RSS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='feeds.category')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a propriétaire le flux RSS.', on_delete=django.db.models.deletion.CASCADE, related_name='rss_feeds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
