# Generated by Django 5.1.6 on 2025-05-18 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout du flux par l'utilisateur.")),
                ('feed', models.ForeignKey(help_text="Flux RSS auquel l'utilisateur est abonné.", on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='feeds.rssfeed')),
                ('user', models.ForeignKey(help_text='Utilisateur abonné au flux RSS.', on_delete=django.db.models.deletion.CASCADE, related_name='user_rss_feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feed')},
            },
        ),
    ]
