# Generated by Django 5.1.4 on 2024-12-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la catégorie.')),
            ],
        ),
    ]
