# Generated by Django 5.1.4 on 2024-12-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Catégorie associée au flux RSS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='feeds.category'),
        ),
    ]
