# Generated by Django 5.1.4 on 2024-12-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_rssfeed_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Image associée à la catégorie.', null=True, upload_to='categories/'),
        ),
    ]
