# Generated by Django 5.1.4 on 2024-12-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Nom de la tâche.', max_length=255, unique=True)),
                ('repeat_time', models.IntegerField(default=120, help_text='Temps de répétition en secondes.')),
            ],
        ),
    ]
